"""baseline schema

Revision ID: a48a2805d933
Revises: 
Create Date: 2026-06-25 08:46:42.935376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a48a2805d933'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_versions_created_at'), 'app_versions', ['created_at'], unique=False)
    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('opens_at', sa.DateTime(), nullable=False),
    sa.Column('closes_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('confederation', sa.Enum('UEFA', 'CONMEBOL', 'CONCACAF', 'CAF', 'AFC', 'OFC', name='confederation'), nullable=False),
    sa.Column('group_name', sa.String(length=1), nullable=True),
    sa.Column('elo_rating', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('market_value_eur', sa.BigInteger(), nullable=True),
    sa.Column('avg_age', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('world_cup_appearances', sa.Integer(), nullable=True),
    sa.Column('best_wc_result', sa.String(length=20), nullable=True),
    sa.Column('avg_goals_for', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('avg_goals_against', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('xg_for', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('xg_against', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('form_5', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('form_10', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('form_20', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('flag_url', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tournament_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('simulations_count', sa.Integer(), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=True),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('group', 'r32', 'r16', 'qf', 'sf', 'third', 'final', name='matchphase'), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_b_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=1), nullable=True),
    sa.Column('match_date', sa.DateTime(), nullable=True),
    sa.Column('venue', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('is_neutral', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'live', 'finished', name='matchstatus'), nullable=True),
    sa.Column('match_number', sa.Integer(), nullable=True),
    sa.Column('bet_deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_table('page_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('country_name', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('device', sa.String(length=20), nullable=True),
    sa.Column('browser', sa.String(length=40), nullable=True),
    sa.Column('os', sa.String(length=40), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_views_created_at'), 'page_views', ['created_at'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('market_value_eur', sa.BigInteger(), nullable=True),
    sa.Column('is_injured', sa.Boolean(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('impact_weight', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('exact_scores', sa.Integer(), nullable=True),
    sa.Column('correct_results', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('invite_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=False),
    sa.Column('score_b', sa.Integer(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'match_id', name='uq_user_match_bet')
    )
    op.create_table('bot_decision_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('bet_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=True),
    sa.Column('old_a', sa.Integer(), nullable=True),
    sa.Column('old_b', sa.Integer(), nullable=True),
    sa.Column('new_a', sa.Integer(), nullable=True),
    sa.Column('new_b', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('prob_a', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('prob_draw', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('prob_b', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('telegram_sent', sa.Boolean(), nullable=True),
    sa.Column('slack_sent', sa.Boolean(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_decision_logs_created_at'), 'bot_decision_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_bot_decision_logs_match_id'), 'bot_decision_logs', ['match_id'], unique=False)
    op.create_table('group_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=False),
    sa.Column('score_b', sa.Integer(), nullable=False),
    sa.Column('xg_a', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('xg_b', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('result', sa.Enum('a', 'draw', 'b', name='match_outcome'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('poll_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('suggestion', sa.String(length=500), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['poll_options.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'user_id', name='uq_poll_user_vote')
    )
    op.create_table('simulations_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('data_hash', sa.String(length=64), nullable=False),
    sa.Column('prob_a', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('prob_draw', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('prob_b', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('lambda_a', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('lambda_b', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('xg_a', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('xg_b', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('top_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('simulations_count', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('user_group_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('inviter_user_id', sa.Integer(), nullable=False),
    sa.Column('invitee_user_id', sa.Integer(), nullable=True),
    sa.Column('invitee_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='groupinvitestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('champion_pick_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['champion_pick_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_user_group_member')
    )
    op.create_table('poll_vote_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['poll_options.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vote_id'], ['poll_votes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_vote_history')
    op.drop_table('user_group_members')
    op.drop_table('user_group_invites')
    op.drop_table('simulations_cache')
    op.drop_table('poll_votes')
    op.drop_table('match_results')
    op.drop_table('group_messages')
    op.drop_index(op.f('ix_bot_decision_logs_match_id'), table_name='bot_decision_logs')
    op.drop_index(op.f('ix_bot_decision_logs_created_at'), table_name='bot_decision_logs')
    op.drop_table('bot_decision_logs')
    op.drop_table('bets')
    op.drop_table('user_groups')
    op.drop_table('rankings')
    op.drop_table('poll_options')
    op.drop_table('players')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_page_views_created_at'), table_name='page_views')
    op.drop_table('page_views')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('matches')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('tournament_simulations')
    op.drop_table('teams')
    op.drop_table('site_config')
    op.drop_table('polls')
    op.drop_index(op.f('ix_app_versions_created_at'), table_name='app_versions')
    op.drop_table('app_versions')
    # ### end Alembic commands ###
